name: dblp
remove_h: null
datadir: 'data/dblp/'
node_class : 0
node_type : 'author'
node_feature_size : 8
node_feature_types :  [0,1] #[0,1,2,3,4,5]
feature_selection_method : 'frequency' #'variance'
threshold : 0.829 #author 0.95,paper 0.99